name: spaghetti-platform
static_sites:
- build_command: npm ci && npm run build
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: twitchyvr/Spaghetti
  name: frontend
  output_dir: /dist
  source_dir: /src/frontend
  routes:
  - path: /
  envs:
  - key: VITE_API_BASE_URL
    value: /api
  - key: VITE_ENVIRONMENT
    value: production
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: twitchyvr/Spaghetti
  name: api
  routes:
  - path: /api
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    value: Production