name: spaghetti-platform
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: twitchyvr/Spaghetti
  name: frontend
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_BASE_URL
    value: /api
  - key: VITE_ENVIRONMENT
    value: production