name: spaghetti-platform
services:
- name: react-frontend
  dockerfile_path: Dockerfile
  source_dir: src/frontend
  github:
    branch: master
    deploy_on_push: true
    repo: twitchyvr/Spaghetti
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 60
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_BASE_URL
    value: /api
  - key: VITE_ENVIRONMENT
    value: production